---
title: "netcdf_practice"
author: "ShujieWang"
date: "January 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(ncdf4)
library(dplyr)
library(tidyr)
library(ggplot2)


```

# read in data from a file

```{r}
nc<-nc_open("data/WG2013CTD.nc")
print(nc)

```


```{r}
#ncvar_get

vars<-attributes(nc$dim)$names
salinity <-ncvar_get(nc,"sal")
time_mat <- ncvar_get(nc,"time")
depth <- ncvar_get(nc,"z")


```


# reformat the data


change the matlab date format to R date format
```{r}
time <- as.POSIXct((time_mat + 719529)*86400, origin = "1970-01-01", tz = "UTC")
```
coerce into a data frame

```{r}
salinity_data <- as.data.frame(salinity) 
```

assign column names to depth values

```{r}
names(salinity_data) <- as.character(depth)
```

reshape the data and add time
```{r}
salinity_data <- salinity_data %>% 
  mutate(time=time) %>% 
  gather(key="depth",value="salinity",-time) %>% 
  mutate(depth=as.numeric(depth))
```

# plots
```{r}
ggplot(salinity_data,mapping=aes(x=time,y=depth,fill=salinity))+
  geom_raster()

```
```{r}

ggplot(salinity_data, aes(x = salinity,
                          y = depth,
                          group = time,
                          color = time)) +
    geom_line(size = .1) +
    scale_y_reverse() +
    theme_bw() +
    ylab("Depth (m)") +
    xlab("Salinity (psu)") +
    theme(legend.title = element_blank())

```

