---
title: "Ropensci_demo"
author: "ShujieWang"
date: "January 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("rnoaa")  
# install.packages("ncdf4")

library(rnoaa)
library(ncdf4)
library(ggplot2)

```

```{r}
bd <- buoy(dataset="cwind",buoyid=46080,year=2018,datatype="c")
```

```{r}
wind_speed <- data.frame(time=as.POSIXct(bd$data$time), speed=bd$data$wind_spd, stringAsFactors=F)

```

```{r}
ggplot(wind_speed, aes(x=time,y=speed)) +
  geom_point()
```


```{r}
# install.packages("mapr", dependencies = TRUE)
library(mapr)
library(spocc)

```

plot locations of GBIF species occurrence data for grizzly and polar bear
```{r}
spp <- c("Ursus arctos","Ursus maritimus","Ursus americanus kermodei") 

bears <- occ(query=spp,
             from="gbif",
             has_coords=T,
             limit=500)


```

```{r}

map_leaflet(bears, size = 1, color = c("black", "gray","pink"), alpha = 1)

```

```{r}
spirit_bears <- bears$gbif$data$Ursus_americanus_kermodei

spirit_bears1 <- bears$gbif$data$Ursus_arctos

spirit_bears2 <- bears$gbif$data$Ursus_maritimus

```


# read netcdf data

```{r}



```







